export const CHANGE_CATEGORY = "CHANGE_CATEGORY";
export const CHANGE_DIFFICULTY = "CHANGE_DIFFICULTY";
export const CHANGE_TYPE = "CHANGE_TYPE";
export const CHANGE_NUM = "CHANGE_NUM";
export const CHANGE_PLAYER = "CHANGE_PLAYER";
export const CHANGE_SCORE = "CHANGE_SCORE";
